name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Start thor solo
      run:  make solo-up
      id: start-solo
    - name: Run tests with Maven
      id: run-tests
      run: mvn -B test
    - name: Stop thor solo
      id: stop-solo
      if: always()
      run: make solo-down
