name: Java CI with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 8
      uses: actions/setup-java@v3
      with:
        java-version: '8'
        distribution: 'temurin'
        cache: maven
    - name: Run tests with Maven
      env:
        privateKey: ${{ secrets.TEST_PRIVATE_KEY }}
        sponsorPrivateKey: ${{ secrets.TEST_SPONSOR_KEY }}
        nodeProviderUrl: ${{ secrets.TEST_NODE_PROVIDER_URL }}
        nodeWSProviderUrl: ${{ secrets.TEST_NODE_WSPROVIDER_URL }}
        timeout: "10000"
      run: mvn -B test
